version: "3.3"
services:
  influxdb:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=influxdb"
    container_name: influxdb
    image: influxdb:1.8.10
    expose:
      - 8086
    restart: unless-stopped
    volumes:
      - "influxdb-storage:/var/influxdb/data"
    env_file:
      - ./credentials.env
    ports:
      - 8086:8086

  telegraf:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=telegraf"
    container_name: telegraf
    build:
      context:
        ./telegraf
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run:/var/run:ro
    env_file:
      - ./credentials.env
    restart: unless-stopped
    links:
      - influxdb
    depends_on:
      - influxdb
  grafana:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=grafana"
    container_name: grafana
    image: grafana/grafana:8.3.4
    environment:
      - GF_INSTALL_PLUGINS=https://grafana.com/api/plugins/gowee-traceroutemap-panel/versions/0.3.0/download;gowee-traceroutemap-panel
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - "grafana-storage:/var/lib/grafana"
    links:
      - "influxdb"
    depends_on:
      - "influxdb"
      - "telegraf"
volumes:
  grafana-storage:
    external: true
  influxdb-storage:
    external: true
